name: Triggered by Repo A

on:
  repository_dispatch:
    types: [trigger]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo B
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Checkout Repo A
      uses: actions/checkout@v3
      with:
        repository: contact-deepak/A
        path: A

    - name: Compile and Run Java Program
      run: |
        cd repo-a
        javac add.java
        java add < ../input.txt > output.txt

    - name: Display Output
      run: cat output.txt
