name: Triggered by Repo A

on:
  repository_dispatch:
    types: [trigger]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo A2
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Checkout Repo A
      uses: actions/checkout@v3
      with:
        repository: contact-deepak/A
        token: ${{ secrets.REPO_A2_PAT }}
        path: A

    - name: List directory contents
      run: |
        ls -R

    - name: Compile and Run Java Program
      run: |
        cd A
        javac add.java

    - name: Display Output
      run: cat A/output.txt || echo "output.txt not found"
