name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Compile Java Program
      run: javac add.java

    - name: Run Java Program
      run: java add > A/output.txt  # Output to file

    - name: Display Output
      run: cat A/output.txt  # Display the content of the output file

    - name: Archive Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: java-build
        path: .
