name: Triggered by Repo A1

on:
  repository_dispatch:
    types: [trigger]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo A2
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Checkout Repo A1
      uses: actions/checkout@v3
      with:
        repository: contact-deepak/A
        token: ${{ secrets.REPO_A2_PAT }}
        path: A

    - name: List directory contents
      run: |
        ls -R

    - name: Compile and Run Java Program
      run: |
        cd A
        javac add.java
        java add < ../input.txt > output.txt

    - name: Display Output
      run: cat repo-a1/output.txt
