name: Triggered by Repo A1

on:
  repository_dispatch:
    types: [trigger]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo A2
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Checkout Repo A1
      uses: actions/checkout@v3
      with:
        repository: contact-deepak/A1
        token: ${{ secrets.REPO_A2_PAT }}
        path: A

    - name: Compile Java Program
      run: javac add.java

    - name: Run Java Program
      run: java add > A/output.txt  # Output to file

    - name: Display Output
      run: cat A/output.txt  # Display the content of the output file

    - name: Archive Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: java-build
        path: .    

    
